organisation: sharksmhi

repos:
  main: SHARKtools

  plugins:
    - SHARKtools_ctd_processing
    - SHARKtools_pre_system_Svea
    - SHARKtools_algaware

  help_repos:
    - svepa
    - sharkpylib
    - file_explorer
    - ctdpy
    - ctd_processing
    - ctdvis
    - profileqc
    - pre_system_svea
    - algaware